# Configure the Public Name and Description here
# For Deleting local builds (Don't use this unless necessary): flutter clean
# For initializing firebase hosting (Only if previous setting was lost): firebase init hosting
# For running the app locally (HTML Renderer): flutter run -d chrome --web-renderer html
# For generating a production build (HTML Renderer): flutter build web --web-renderer html --release
# For deploying production to firebase hosting: firebase deploy --only hosting
name: BruneiEats
description: A new Flutter project used for a Brunei Restaurant Recommendations App that's.

# version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  responsive_grid: ^1.2.1+1
  smooth_star_rating: ^1.1.1
  sliver_fab: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # For details regarding assets, see
  # https://flutter.dev/assets-and-images
  assets:
    - assets/friendlyeater.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
